# Generated by Django 5.0.1 on 2025-10-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_account', models.CharField(max_length=64)),
                ('destination_account', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('PROCESSED', 'PROCESSED')], max_length=10)),
                ('created_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
